version: "3.9"
services:
  library-management:
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - payment-gate
    command:
      - "library-management.jar"
    ports:
      - "8090:8080"
    networks:
      - library-net
  payment-gate:
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    command:
      - "payment-gate.jar"
    ports:
      - "8081:8080"
    networks:
      - library-net
  reporting:
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - library-management
    command:
      - "reporting.jar"
    ports:
      - "8082:8080"
    networks:
      - library-net
  self-service-kiosk:
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - library-management
    command:
      - "self-service-kiosk.jar"
    ports:
      - "8083:8080"
    networks:
      - library-net
  oauth2-client:
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    command:
      - "oauth2-client.jar"
    ports:
      - "8084:8080"
    networks:
      - library-net
networks:
  library-net: