version: "3.9"
services:
  library-management:
    container_name: library-management
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - payment-gate
    command:
      - "library-management.jar"
    ports:
      - "8080:8080"
    networks:
      - library-net
  payment-gate:
    container_name: payment-gate
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    command:
      - "payment-gate.jar"
    ports:
      - "8081:8080"
    networks:
      - library-net
  reporting:
    container_name: reporting
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - library-management
    command:
      - "reporting.jar"
    ports:
      - "8082:8080"
    networks:
      - library-net
  self-service-kiosk:
    container_name: self-service-kiosk
    restart: on-failure
    image: quay.io/juraj_marcin/pa165-library-management-system:latest
    build: .
    depends_on:
      - library-management
    command:
      - "self-service-kiosk.jar"
    ports:
      - "8083:8080"
    networks:
      - library-net
  prometheus:
    container_name: prometheus
    restart: on-failure
    image: prom/prometheus:latest
    depends_on:
      - library-management
      - payment-gate
      - reporting
      - self-service-kiosk
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - library-net
  grafana:
    container_name: grafana
    restart: on-failure
    image: grafana/grafana-enterprise:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml
      - ./grafana/provisioning/dashboards/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/grafana-dashboard.json
      - ./grafana/provisioning/dashboards/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/grafana-dashboard.json"
    networks:
      - library-net
networks:
  library-net: