management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      show-components: always
library-management:
  url: http://localhost:8090
server:
  port: 8083
  error:
    include-message: always
