spring:
    datasource:
        url: jdbc:h2:mem:exampleDb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
paymentgateurl: http://localhost:8081/
paymentgatecallback: http://localhost:8080/payments/