management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  datasource:
    url: jdbc:h2:mem:exampleDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
payment-gate:
  url: http://localhost:8081/
  callback: http://localhost:8080/payments/
server:
  port: 8080
  error:
    include-message: always
