management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      show-components: always
library-management:
  url: http://localhost:8080/
server:
  port: 8082